### ISSUE TITLE
Request: Filter message source to a single text channel

### ISSUE THREAD

**Issue by BreadMoirai** [Reimnop/Discord4Fabric#10]
Currently all message the bot receives are forwarded to minecraft. I would like it if only the messages sent in the specified channel in the config are forwarded to minecraft

**Comment by Reimnop** [comment]
That was supposed to have been fixed in version 1.1.2. Is it doing the same thing again?

**Comment by BreadMoirai** [comment]
Sorry I had the wrong version installed! Ty
