### ISSUE TITLE
Bug: Mentions in discord show up as raw format in minecraft

### ISSUE THREAD

**Issue by BreadMoirai** [Reimnop/Discord4Fabric#11]
Affected Version(s): 1.1.2

`@Someone` on discord will show up as
`<@123124121231241254>` on minecraft

**Comment by Reimnop** [comment]
Was fixed in the latest commit, but still not pushed. I'm still working on other bugs and features before pushing this one as version 1.2.0. Thanks for the report!

**Comment by sdaddy** [comment]
> Was fixed in the latest commit, but still not published. I'm still working on other bugs and features before publishing this one as version 1.2.0. Thanks for the report!

Is one of these new features the ability to @ a Discord account in a message? I would like to @ myself in the Server Stop message to get notified. Right now it just shows up as plain text. Thanks and keep up the great work! :)

**Comment by Reimnop** [comment]
> > Was fixed in the latest commit, but still not published. I'm still working on other bugs and features before publishing this one as version 1.2.0. Thanks for the report!
> 
> Is one of these new features the ability to @ a Discord account in a message? I would like to @ myself in the Server Stop message to get notified. Right now it just shows up as plain text. Thanks and keep up the great work! :)

Unfortunately that's not it, but you can achieve the same thing by putting `<@discordid>` in your message format in the config.

**Comment by Reimnop** [comment]
Closing this as completed as it was fixed (+ configurable ping format).
