### ISSUE TITLE
Request: Designate discord replies

### ISSUE THREAD

**Issue by DDR-Khat** [Reimnop/Discord4Fabric#12]
In discord, you can right-click on a message and "reply" to it, linking context for the sake of knowing what someone is referring to.

I think the easiest implementation is;
[User on Discord] (In reply to earlier message) : I don't think that is quite the case.

The nicer one albeit would take a lot more work is;
[User on Discord] (Replying: first four words of message) : Well, maybe but I don't think so.

**Comment by Reimnop** [comment]
Implemented!
