### ISSUE TITLE
Discord emoji don't show up in embeds

### ISSUE THREAD

**Issue by NotToxel** [Reimnop/Discord4Fabric#13]
![image](https://user-images.githubusercontent.com/29763976/173418336-5f733e57-245c-464e-b5b6-890bc777adc4.png)
![image](https://user-images.githubusercontent.com/29763976/173418370-7d63d8ee-1c70-4ee8-b1e8-67bf9ab2199c.png)
My discord server emotes don't show up inside the embed, it works for non-embedded messages like server start and stop
![image](https://user-images.githubusercontent.com/29763976/173418470-13cf9a9b-2dec-473b-8e01-a45618a05c8b.png)

**Comment by Reimnop** [comment]
Sorry, forgot to implement it for death messages too!
