### ISSUE TITLE
Nickname placeholder doesn't use guild nickname

### ISSUE THREAD

**Issue by SulpherStaer** [Reimnop/Discord4Fabric#14]
At the moment, the discord user name uses their global name. This can lead to confusions. If this is already possible I couldn't find it in the documentations.

It would be nice if guild/  server spesific names could be used instead

**Comment by Reimnop** [comment]
Reading this again, you want to use server nickname instead of global name in Minecraft instead?

**Comment by DDR-Khat** [comment]
> Reading this again, you want to use server nickname instead of global name in Minecraft instead? If so, this is already possible: `[%d4f:nickname% on Discord] %d4f:message%`

Currently it is not the case that it shows the _server_ nickname.
![image](https://user-images.githubusercontent.com/66983153/177736625-9d5d38df-ad3e-4671-bd15-c9097a1aee69.png)
![image](https://user-images.githubusercontent.com/66983153/177736665-3e13710d-c3bf-4f9e-9402-c4dfe134a4d1.png)

But just the users normal one.

**Comment by Reimnop** [comment]
Ah, in that case I'll label this as bug

**Comment by SulpherStaer** [comment]
This still doesn't appear to be fixed.
![image](https://user-images.githubusercontent.com/5037244/178262500-34f29590-7e79-4ea8-9262-e75471624095.png)
![image](https://user-images.githubusercontent.com/5037244/178262526-06cc1990-ecb3-44da-a5d0-07e0f679dc9a.png)
![image](https://user-images.githubusercontent.com/5037244/178262595-70efe77b-8705-4a14-8da8-e8c2e464eef2.png)

It is still grabbing my username, and not the server nickname.

**Comment by Reimnop** [comment]
Did you compile the mod yourself?
If you have grabbed a build from CurseForge, it's because I haven't pushed the fixed build

**Comment by SulpherStaer** [comment]
That might be it. I am currently using 1.6 👍
