### ISSUE TITLE
Request: Allow Linked MC account tagging

### ISSUE THREAD

**Issue by DDR-Khat** [Reimnop/Discord4Fabric#20]
So now that account linking is a thing, can it be made that if I type their in-Minecraft username in Minecraft, it converts to the linked discord ?

@Notch in game for example would convert into @theRealNotch#2219 to correctly tag them? _(This one is a pure example, I don't know notch's discord)_

This would help with the problem of people having spaces in their discord names as that won't get properly tagged unless you also involve their #code. If you know all that, you are probably in discord anyway, eliminating the benefit of in-game tagging.

**Comment by Reimnop** [comment]
Implemented!

**Comment by DDR-Khat** [comment]
This works amazingly! Thank you for the great work!
