### ISSUE TITLE
Request: To show skin on discord chat and compatible with fabrictailor

### ISSUE THREAD

**Issue by sadlyborger** [Reimnop/Discord4Fabric#30]
As said in the title.
To show discord bot the skin that we are using and be compatible with fabrictailor.

**Comment by samolego** [comment]
Just saw this; perhaps have a look at https://github.com/QuiltServerTools/BlockBot/issues/26 and perhaps https://github.com/QuiltServerTools/BlockBot/pull/39/commits/b4db31003508518dbc2cf2e7659f9e4ad6951ddb

**Comment by samolego** [comment]
You can even use builtin 1.9.0 method in `TailoredPlayer` ;)
