### ISSUE TITLE
[Feature Request] !tps and !list commands the bot can execute from discord

### ISSUE THREAD

**Issue by Miv2nir** [Reimnop/Discord4Fabric#31]
Hello! I think it'd be great if you could implement a feature in which there'd be certain commands executable from discord, like !tps or !list, so that one could see the stats more in detail.
Perhaps it would also be great to be able to specify which command to execute exactly, like if !tps would return an output of /spark tps.

**Comment by AchalS-iglu** [comment]
+1

**Comment by Reimnop** [comment]
Implemented!
