### ISSUE TITLE
[Feature] Console channel

### ISSUE THREAD

**Issue by ChristopherHaws** [Reimnop/Discord4Fabric#33]
One feature from DiscordSRV which I used all the time was the ability to have one of my discord channels as a Minecraft ["console"](https://docs.discordsrv.com/config/#DiscordConsoleChannelId) where I could view logs and execute commands from within discord. I would love this feature to be added to this mod as well.

Thanks! :)

**Comment by gadget78** [comment]
could we have a `!console` command in discord listening channel, only useable by listed OPs (or use the linked OP?)
if thats easier ?

**Comment by Reimnop** [comment]
Don't worry, I can implement the full console channel, it's just that it's not top priority on my checklist at the moment.

**Comment by Reimnop** [comment]
Implemented!
