### ISSUE TITLE
discord won't display that you left ingame or use /vanish

### ISSUE THREAD

**Issue by sadlyborger** [Reimnop/Discord4Fabric#34]
It seems that the vanish fake leave doesn't show in the discord.

![image](https://user-images.githubusercontent.com/108927538/179448984-c1d43d8c-e6bd-4986-87e4-383097819c30.png)
![image](https://user-images.githubusercontent.com/108927538/179449063-01a81666-d3cd-4b32-a856-eb6c13b48a22.png)

**Comment by Reimnop** [comment]
Check your vanish config. Is it configured to show fake leave/join messages?

**Comment by sadlyborger** [comment]
Yes, it is. 
![image](https://user-images.githubusercontent.com/108927538/179452213-a905137f-4bd1-40fa-8288-3d94f070bf41.png)

**Comment by Reimnop** [comment]
Are you using the latest version of the mod? (1.7.0)

**Comment by sadlyborger** [comment]
Yes. Do I have to delete old files? as show above picture. It is 1.7.0

**Comment by Reimnop** [comment]
Could you give me a modlist?

**Comment by sadlyborger** [comment]
Modlist is all the mods install in the server right?

**Comment by Reimnop** [comment]
Yes, I need that

**Comment by sadlyborger** [comment]
Here's all the mods that our server uses. Thank you very much.

![image](https://user-images.githubusercontent.com/108927538/179454772-b295b30c-26f9-4adb-904d-986e4486c321.png)
![image](https://user-images.githubusercontent.com/108927538/179454784-f237969a-8131-4df5-ac80-0720b6e6e642.png)

**Comment by onycius** [comment]
I'm not sure if this is related, but i get this in my startup log when using vanish + d4f

https://pastebin.com/TeNnki01
