### ISSUE TITLE
Request: Can add on two different discord server

### ISSUE THREAD

**Issue by sadlyborger** [Reimnop/Discord4Fabric#35]
As said in above, is it possible to have it on 2 or more server and only using 1 bot instead of creating a new one? I just have to add the bot in the other server? It's just a request. This is rare on other discord to fabric chat so this might be a good one reason to make more people use it.
Btw, still love the mod. 11/10

**Comment by Reimnop** [comment]
Unfortunately the current architecture of the mod doesn't support this, and it'd take major rewrite to do so. This feature will not be implemented.

**Comment by sadlyborger** [comment]
Okay, thank you.
