### ISSUE TITLE
Separate releases for each version of Minecraft in Modrinth

### ISSUE THREAD

**Issue by 3stantedja** [Reimnop/Discord4Fabric#36]
Hi!
Coming from packwiz/packwiz#142, would it be possible to separate the mod releases for each version of Minecraft in Modrinth? Currently when I use `packwiz` to manage my server-side modpack it will download the 1.18.2 version of the mod even if the modpack has been defined to be only compatible with 1.19.

As stated by @comp500:
> [...] they need to create separate versions for 1.18 and 1.19, as the metadata currently implies that _both_ files support _both_ 1.18 and 1.19!

**Comment by Reimnop** [comment]
Didn't think about this, thank you for the feedback!
