### ISSUE TITLE
Request: Markdown support

### ISSUE THREAD

**Issue by DDR-Khat** [Reimnop/Discord4Fabric#4]
`_Italic_` etc etc.
(Bonus points for emoji support)

This is for both ways.

**Comment by Reimnop** [comment]
Sorry for the very late reply! This mod aims to not modify any message sent by users. You can use a mod like [StyledChat](https://github.com/Patbox/StyledChat) for the sort of thing. Are you okay with that instead?

**Comment by DDR-Khat** [comment]
I am fine with using StyledChat for messages in the Minecraft Server, however messages are currently coming in from Discord without having their discord-styling applied if it's applicable to Minecraft.
``_Test message_`` for example in Discord is; _Text message_ but displays in Minecraft as; the former.

**Comment by Titaniumtown** [comment]
<https://github.com/Gegy/markdown-chat> has an API that could be used if `markdown-chat` is installed

**Comment by Reimnop** [comment]
Ah, thank you for the clarification!

**Comment by Reimnop** [comment]
Both markdown and emojis have been implemented, closing this issue now.
