### ISSUE TITLE
Can it be updated at 1.19 also? The new update?

### ISSUE THREAD

**Issue by sadlyborger** [Reimnop/Discord4Fabric#40]
I have updated my fabric not noticing its in 1.19.1. Can back port the new update to 1.19? or at least be compatible with 1.19.x?

`29.07 19:59:51 [Server] main/ERROR Failed to start the minecraft server
29.07 19:59:51 [Server] INFO java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'd4f'!
29.07 19:59:51 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.6.jar:?]
29.07 19:59:51 [Server] INFO at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.6.jar:?]
29.07 19:59:51 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.6.jar:?]
29.07 19:59:51 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.6.jar:?]
29.07 19:59:51 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.6.jar:?]
29.07 19:59:51 [Server] INFO at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
29.07 19:59:51 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
29.07 19:59:51 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
29.07 19:59:51 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.6.jar:?]
29.07 19:59:51 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.6.jar:?]
29.07 19:59:51 [Server] INFO at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [Fabric_Latest_1.19.jar:0.11.0]
29.07 19:59:51 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_2556$class_7602
29.07 19:59:51 [Server] INFO at me.reimnop.d4f.listeners.MinecraftEventListeners.init(MinecraftEventListeners.java:248) ~[discord4fabric-1.19.1-1.8.1.jar:?]
29.07 19:59:51 [Server] INFO at me.reimnop.d4f.Discord4Fabric.initDiscord(Discord4Fabric.java:100) ~[discord4fabric-1.19.1-1.8.1.jar:?]
29.07 19:59:51 [Server] INFO at me.reimnop.d4f.Discord4Fabric.onInitialize(Discord4Fabric.java:58) ~[discord4fabric-1.19.1-1.8.1.jar:?]
29.07 19:59:51 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.6.jar:?]
29.07 19:59:51 [Server] INFO ... 8 more
29.07 19:59:51 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2556$class_7602
29.07 19:59:51 [Server] INFO at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
29.07 19:59:51 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
29.07 19:59:51 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.6.jar:?]
29.07 19:59:51 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.6.jar:?]
29.07 19:59:51 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
29.07 19:59:51 [Server] INFO at me.reimnop.d4f.listeners.MinecraftEventListeners.init(MinecraftEventListeners.java:248) ~[discord4fabric-1.19.1-1.8.1.jar:?]
29.07 19:59:51 [Server] INFO at me.reimnop.d4f.Discord4Fabric.initDiscord(Discord4Fabric.java:100) ~[discord4fabric-1.19.1-1.8.1.jar:?]
29.07 19:59:51 [Server] INFO at me.reimnop.d4f.Discord4Fabric.onInitialize(Discord4Fabric.java:58) ~[discord4fabric-1.19.1-1.8.1.jar:?]
29.07 19:59:51 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.6.jar:?]`

**Comment by gadget78** [comment]
as far as im aware, this is supported, looking at this commit .. 
https://github.com/Reimnop/Discord4Fabric/commit/0416feadb8e0655b7184ddc84dde692bdc512705

**Comment by sadlyborger** [comment]
> 

Hello, I also don't know about it. But do you have any idea why its giving me an error?

**Comment by Reimnop** [comment]
Hello, this is happening because of some text changes in 1.19.1, it is not backwards compatible with 1.19. However, I will not make a backport to 1.19 as it's already troublesome maintaining 2 separate ports given the limited time I have. Thank you for understanding!
