### ISSUE TITLE
[Feature/Enhancement:request] new Constraint based on the message

### ISSUE THREAD

**Issue by gadget78** [Reimnop/Discord4Fabric#41]
so a Constraint based on message events
`minecraft_message`
and `discord_message`

a simple example would be ... 
`{
  "minecraft_message": {
    "requires": [
      {
       "linked_account",
        "%d4f:message%": "!request goggles"
      }
    ],
    "actions": [
      {
        "id": "run_command",
        "value": "give %player:name_unformatted% goml:goggles"
      }
    ]
  }
}`

**Comment by gadget78** [comment]
in addition to message, advancement match would be cool to ... 
so we could then create a "CUSTOM_EVENT" to assign a role depending on matched advancement !

**Comment by gadget78** [comment]
wow Thankyou for adding my feature suggestions ! and so quickly to... 

just gone to try these out bet getting the red "An unexpected error occured! Check logs for more details" in game.. 
sadly not one of your logger errors ?? not sure where they are supposed to show, the logs on console are very large... 

seems that its tripping over how im entering the message to check/compare  ??..  if i remove the `: "requestgoggles"` from after the mc_message i dont get ANY errors, where i thought i should ?? 
```
{
  "minecraft_message": {
    "requires": [
      "linked_account",
      "mc_message": "requestgoggles"
    ],
    "actions": [
      {
        "id": "run_command",
        "value": "give %player:name_unformatted% goml:goggles"
      }
    ]
  }
}
```

**Comment by Reimnop** [comment]
That syntax is not really how I implemented it, I'll write docs later

**Comment by gadget78** [comment]
arrr ok, i guessed, and used a more json looking syntax ... 
i got the constraints correct from looking at source, but couldnt work out the syntax from source !

just tested with brackets etc, and works flawlessly ! roles, messages, all working :)
Thankyou ! 
with these constraint combo's it makes this system VERY powerful and versatile !
