### ISSUE TITLE
Death messages don't work

### ISSUE THREAD

**Issue by CalXee** [Reimnop/Discord4Fabric#42]
Death messages don't get logged in discord. I tried dying to mobs, nothing happens. Is it because I removed the description text for death messages? I tested on 1.19.1

**Comment by gadget78** [comment]
Have you tried putting description back ?
Have your checked config to see if it's still enabled?

**Comment by gadget78** [comment]
althou i have found out that NO advancement announcements are now coming through to discord now either ... 
also been getting alot of these errors  like this .. 
`Encountered 429 on route PATCH/channels/{channel_id} with bucket 9852`
if that means anything to you..

**Comment by dghodgson** [comment]
I'm also running into this issue, deaths are not getting announced in discord

**Comment by V-lpen** [comment]
Experiencing the same issue on discord4fabric-1.19.1-1.10.0.jar
