### ISSUE TITLE
Error 1.19.1 Quilt

### ISSUE THREAD

**Issue by Diyagi** [Reimnop/Discord4Fabric#43]
Hello,
Im trying to setup this mod, but it keeps spamming this error on the console.
I think all the information u need is in the log, tell me if u need anything else or if im doing something dumb
[greencraft_minecraft.1.lu14orz0y20vdphgq30c1zpn1_logs.txt](https://github.com/Reimnop/Discord4Fabric/files/9232952/greencraft_minecraft.1.lu14orz0y20vdphgq30c1zpn1_logs.txt)
.

**Comment by Reimnop** [comment]
Looks like a fixed issue. Can you try a build from [here](https://github.com/Reimnop/Discord4Fabric/actions/runs/2764370628)?

**Comment by Diyagi** [comment]
Oh, thank you, it worked. 
I actually downloaded the last artifact before, but it had the same version so i thought that it was the same from modrinth.
