### ISSUE TITLE
Request: Role on Join Status

### ISSUE THREAD

**Issue by DDR-Khat** [Reimnop/Discord4Fabric#5]
The ability to give/remove a role from a member of discord
This can allow a clear look at the user look of whom is "online" or "offline" by giving them a specific "online" discord role with coloring or something.

**Comment by Reimnop** [comment]
Will be implemented as events that run on user leave/join, player death, advancement, etc

**Comment by Reimnop** [comment]
Now possible via Custom Events. See [custom events docs](https://github.com/Reimnop/Discord4Fabric/blob/main/CUSTOM_EVENTS.md)
