### ISSUE TITLE
[Bug]?? grant_role seems to always throw an error ? 

### ISSUE THREAD

**Issue by gadget78** [Reimnop/Discord4Fabric#63]
as title.. the grant_role action
always seems to throw fault, showing `a Invalid grant_role value format (should be object)` in log .. ? 

which i can see you have coded that error in for a reason .. ? 
```
        if (!(value instanceof JsonObject jsonObject)) {
            Discord4Fabric.LOGGER.error("Invalid grant_role value format (should be object)");
            return;
        }
```
what would be something to look for to fix this issue ? 

this mod is Soo versatile ...

**Comment by Jayspek** [comment]
Also having this issue, any luck?

**Comment by Reimnop** [comment]
Totally forgot about this, can you send me your grant_role value in your custom events config?

**Comment by Jayspek** [comment]
Sure!
{
        "id": "grant_role",
        "value": "1061971471485902979"
      }

**Comment by Reimnop** [comment]
That is definitely the incorrect way to do it; the correct way would be like this:
```json
{
    "id":"grant_role",
    "value": {
        "user":"%linked_account:id%,
        "role":"1061971471485902979"
    }
}```
Don't forget to also add the `linked_account` constraint by doing this:
```json
"requires": [
    "linked_account"
]```

**Comment by Jayspek** [comment]
Oohhh, I see. Thanks for clarifying, my bad.

**Comment by Reimnop** [comment]
You're welcome, apologies for the very late reply
