### ISSUE TITLE
1.19.4 Support? [Really need it right now.] [Question]

### ISSUE THREAD

**Issue by NotFlow69** [Reimnop/Discord4Fabric#72]
When is 1.19.4 support coming out? any **ETA**?

**Comment by Reimnop** [comment]
If you really need 1.19.4 now, there was a PR (#70) that added this. Here's the [Actions](https://github.com/Reimnop/Discord4Fabric/actions/runs/4441920700) run that is associated with it. You can download a build from there.

**Comment by NotFlow69** [comment]
oh ok, thanks a lot
