### ISSUE TITLE
[Crash Bug] Players joining the server in 23w17a crashes the server.

### ISSUE THREAD

**Issue by DorkOrc** [Reimnop/Discord4Fabric#78]
My guess is it has something to do with the unicode handling changes in this snapshot.
![image](https://user-images.githubusercontent.com/16517352/234713718-21a6b5f1-c833-430d-ad9c-bd3f070adf99.png)

**Comment by Reimnop** [comment]
I'm sorry, but I do not support snapshots. You can fork the project to make it work yourself though.
