### ISSUE TITLE
ALL discord chat goes to server

### ISSUE THREAD

**Issue by DDR-Khat** [Reimnop/Discord4Fabric#8]
Currently all chat regardless of channel on discord goes into the Minecraft server.

**Comment by Reimnop** [comment]
That's a huge oversight, thank you for reporting it, and sorry for the inconvenience!

**Comment by Titaniumtown** [comment]
I experience this too, SUPER annoying.

**Comment by Reimnop** [comment]
Fixed in 1.1.2
