### ISSUE TITLE
The mod is spamming this error message

### ISSUE THREAD

**Issue by matheeshapathirana** [Reimnop/Discord4Fabric#86]
The mod spamming this error message in my console,
```
Encountered 429 on route PATCH/channels/{channel_id} with bucket 6e836da6cef38ba2f3dfd8568a4e9631:channel_id=1121458058082660372 Retry-After: 5000 ms Scope: user
```
Please help me to fix this error.

**Comment by Reimnop** [comment]
What's your channel topic update time in your config?

**Comment by matheeshapathirana** [comment]
Oh, I changed it to 3
![image](https://github.com/Reimnop/Discord4Fabric/assets/129346924/04bf296c-2e9e-4d6b-b767-a969fb9b163c)
Should I change it to default?

**Comment by Reimnop** [comment]
That's going to update the topic every 3 ticks, not seconds. Discord has a rate limit for topic update, which is two times per 10 minutes. Exceeding that rate causes issues. I suggest you change it to default or disable it altogether.

**Comment by matheeshapathirana** [comment]
Ok alr, thanks.
